### ISSUE TITLE
Add Oli as a mentor

### ISSUE THREAD

**Issue by oli-obk** [RustBeginners/awesome-rust-mentors#16]
* **Preferred Name**: Oli
* **Github Username or equivalent handle**: oli-obk
* **Pronouns**: He/him
* **Contact**: zulip or github preferred, but discord works, too
* **Spoken Languages**: German and English
* **Topics**: miri, const eval, error messages and other diagnostics, optimizations, MIR

**Comment by yaahc** [comment]
oli, which language is your first one? We updated the template and you probably got in before we push the update. We're _emphasizing_ people's first language

**Comment by yaahc** [comment]
I made a PR and added links for the zulip(directly to const eval :) ) and the official discord invite, let me know if thats good :D

**Comment by oli-obk** [comment]
Ah, you already emphasized German. That's good then. I thouht it was "emphasize preferred" so I emphasized neither

Links lgtm

**Comment by yaahc** [comment]
Hmm, we can reword that, the intent was to emphasize your first language, but maybe its bad to ask people to say that because it could be exposing personal info? I'm not really sure. The main goal here is to make sure people understand if there's a risk of miscommunication. But this might be a solution in search of a problem.
